Repository softeerbootcamp-3rd/Team10-GENE10S, pull requests merged in 2024-02, with the labels that each got.

#5 [#4] entity 생성 및 관계 설정
  back/reservation/HELP.md
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/genesisairport/reservation/ReservationApplication.java
  server/src/main/java/com/genesisairport/reservation/controller/HelloController.java
  server/src/main/java/com/genesisairport/reservation/entity/AvailableTime.java
  server/src/main/java/com/genesisairport/reservation/entity/Car.java
  server/src/main/java/com/genesisairport/reservation/entity/CarImage.java
  server/src/main/java/com/genesisairport/reservation/entity/Coupon.java
  server/src/main/java/com/genesisairport/reservation/entity/Customer.java
  server/src/main/java/com/genesisairport/reservation/entity/MaintenanceImage.java
  server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
  server/src/main/resources/application.yml
  server/src/test/java/com/genesisairport/reservation/ReservationApplicationTests.java
Labels: enhancement

#6 [#1] react 환경 설정
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.json
  client/.vscode/settings.json
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/api/Settings.js
  client/src/api/testConnectionApi.js
  client/src/assets/home-banner.png
  client/src/assets/logo.png
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/index.js
  client/src/pages/Bot.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/NotFound.js
  client/src/pages/Reservation.js
  client/src/styles/components/footer.scss
  client/src/styles/components/header.scss
  client/src/styles/pages/main.scss
  client/src/styles/reset.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: Setup

#10 [#9] 변수 추가 및 수정
  client/src/styles/variables.scss
Labels: enhancement

#13 [#8] 메인 화면 최소 구현
  client/src/assets/logo.png
  client/src/pages/Main.js
  client/src/styles/components/header.scss
  client/src/styles/pages/main.scss
Labels: enhancement

#15 [#7] OAuth 2.0 기능 구현
  client/.gitignore
  client/src/components/Header.js
  client/src/pages/Main.js
  server/src/main/java/com/genesisairport/reservation/Request/LoginRequest.java
  server/src/main/java/com/genesisairport/reservation/Response/LoginResponse.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/HelloController.java
  server/src/main/java/com/genesisairport/reservation/entity/Session.java
  server/src/main/java/com/genesisairport/reservation/respository/CustomerRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/SessionRepository.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
Labels: enhancement

#17 [#14] footer ui 구현
  client/src/assets/logo-facebook.png
  client/src/assets/logo-footer.png
  client/src/assets/logo-url.png
  client/src/assets/logo-x.png
  client/src/components/Footer.js
  client/src/styles/components/footer.scss
  client/src/styles/styles.scss
Labels: enhancement

#22 [#20] js-cookie 라이브러리 추가
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
Labels: bug

#27 [#21] 예약가능날짜 더미 API 작성
  server/.gitignore
  server/src/main/java/com/genesisairport/reservation/Response/ReservationDateResponse.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: enhancement

#23 [#19] profile dummy API 추가
  server/src/main/java/com/genesisairport/reservation/Response/LoginResponse.java
  server/src/main/java/com/genesisairport/reservation/common/ResponseCode.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/request/LoginRequest.java
  server/src/main/java/com/genesisairport/reservation/response/UserResponse.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
Labels: enhancement

#25 [#18] 차량 리스트 조회 API 더미데이터
  server/.gitignore
  server/src/main/java/com/genesisairport/reservation/Response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: enhancement

#29 [#28] 예약정보저장 api 더미 데이터 반환
  server/src/main/java/com/genesisairport/reservation/Response/ReservationPostResponse.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: enhancement

#35 [# 30] 예약내역리스트 api가 더미 데이터를 반환
  server/src/main/java/com/genesisairport/reservation/Response/ReservationListAbstract.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: enhancement

#33 [#26] 세션 테이블에 유저 정보 추가
  client/src/api/Settings.js
  client/src/pages/Main.js
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/entity/Customer.java
  server/src/main/java/com/genesisairport/reservation/entity/Session.java
  server/src/main/java/com/genesisairport/reservation/respository/CustomerRepository.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
  server/src/main/resources/application.yml
Labels: feat

#40 [#31] 차량 리스트 조회 API 개발
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationListAbstract.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#41 [#39] user profile API 기능 개발
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/entity/Car.java
  server/src/main/java/com/genesisairport/reservation/entity/CarImage.java
  server/src/main/java/com/genesisairport/reservation/respository/CarImageRepository.java
  server/src/main/java/com/genesisairport/reservation/service/CarService.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/SessionService.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
Labels: feat

#43 [#38] 예약정보저장 api 개발
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/Coupon.java
  server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationListAbstract.java
  server/src/main/java/com/genesisairport/reservation/respository/CouponRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/CustomerRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#45 [#37] 예약 완료 페이지 ui 구현
  client/.eslintrc.json
  client/.prettierrc.json
  client/.vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/assets/row-separator.svg
  client/src/index.js
  client/src/pages/ReservationComplete.js
  client/src/styles/pages/reservComp.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: feat

#47 [#42] 예약 가능한 날짜 조회 API 수정
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/config/QuerydslConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#51 style: 페이지 공통 속성 추가
  client/src/styles/styles.scss
Labels: feat

#53 [#48] 예약정보저장 api 현재사용자쿠키 기반 동작
  server/.gitignore
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#55 [#54] 예약정보저장 api 반환 내용 변경
  server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#57 [#56] 마이페이지 퍼블리싱
  client/src/assets/settings.png
  client/src/components/Header.js
  client/src/pages/Mypage.js
  client/src/styles/pages/myPage.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: feat

#58 [#49] 예약 가능한 날짜 조회 API 수정
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat, refactor

#60 [#52] 페이지에 파라미터 표시
  client/src/pages/ReservationComplete.js
  client/src/styles/pages/reservComp.scss
  client/src/styles/variables.scss
Labels: feat

#62 [#59] 예약정보저장api request dto cnrk
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
  server/src/main/java/com/genesisairport/reservation/request/ReservationRequest.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#64 [#63] 선택한 서비스가 보이도록 수정
  client/src/pages/ReservationComplete.js
  client/src/styles/pages/reservComp.scss
  client/src/styles/styles.scss
Labels: fix

#71 [#70] 폰트 변수 구조화 및 추가
  client/src/styles/variables.scss
Labels: feat

#73 [#72] 마이페이지내정보 페이지 구성
  client/src/assets/profile-image.png
  client/src/assets/setting.png
  client/src/pages/Mypage.js
  client/src/styles/pages/myPage.scss
Labels: refactor

#75 [#74] 메인 페이지 publishing
  client/src/assets/body-image-1.png
  client/src/assets/body-image-2.png
  client/src/assets/circle.png
  client/src/assets/half-frame-1.png
  client/src/assets/half-frame-2.png
  client/src/assets/progress-arrow-big.png
  client/src/pages/Main.js
  client/src/styles/pages/main.scss
  client/src/styles/styles.scss
Labels: feat

#78 [#77] reservation dto 병합
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationDateResponse.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationListAbstract.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: refactor

#80 [#67] 예약 페이지 구현
  client/src/assets/progress-arrow.svg
  client/src/assets/sample-model.png
  client/src/assets/sample-service.png
  client/src/components/Arrow.js
  client/src/components/Button.js
  client/src/components/Calendar.js
  client/src/components/ModalDate.js
  client/src/components/ModalHeader.js
  client/src/components/ModalInfo.js
  client/src/components/ModalService.js
  client/src/index.js
  client/src/pages/ReservationModal.js
  client/src/styles/components/calendar.scss
  client/src/styles/components/modalHeader.scss
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: feat

#82 [#79] 내정보 페이지 기능추가
  client/package.json
  client/src/pages/Mypage.js
  client/src/styles/pages/myPage.scss
Labels: refactor

#89 [#85] 예약내역페이지 작성
  client/src/components/ProfileCard.js
  client/src/components/ReservationCard.js
  client/src/pages/Mypage.js
  client/src/styles/pages/myPage.scss
Labels: feat, refactor

#91 [#90] 마이페이지 디자인수정
  client/src/assets/mypage-banner.png
  client/src/assets/profile-image.png
  client/src/styles/pages/myPage.scss
Labels: design

#97 fix: 프로필 api에 email 추가
  server/src/main/java/com/genesisairport/reservation/response/UserResponse.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
Labels: fix

#94 feat: 프로필 상세 페이지 퍼블리싱
  client/src/components/Modal.js
  client/src/index.js
  client/src/pages/Profile.js
  client/src/styles/components/modal.scss
  client/src/styles/pages/profile.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: feat

#100 feat: genesis 폰트 추가
  client/src/fonts/GenesisSansHeadKRLight.woff2
  client/src/fonts/GenesisSansHeadKRRegular.woff2
  client/src/fonts/GenesisSansTextKRRegular.woff2
  client/src/styles/variables.scss
Labels: feat

#102 [#96] 예약 가능 여부 조회 API 로직 수정
  server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryImpl.java
Labels: fix

#106 feat: GET user/info API 개발완료
  server/src/main/java/com/genesisairport/reservation/common/CommonDateFormat.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/entity/Customer.java
  server/src/main/java/com/genesisairport/reservation/response/UserResponse.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
Labels: feat

#107 [#104] PATCH /user/info 개발완료
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/request/UserRequest.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
Labels: feat

#108 [#101] /car-list, /list api 반환값에 이미지 경로를 추가 후 마이페이지 반영
  client/src/components/ProfileCard.js
  client/src/components/ReservationCard.js
  client/src/styles/pages/myPage.scss
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix

#110 [#109] 마이페이지 애니메이션 추가
  client/src/components/ProfileCard.js
  client/src/components/ReservationCard.js
  client/src/pages/Mypage.js
  client/src/styles/pages/myPage.scss
Labels: design

#111 [#105] 예약 인트로 페이지 수정
  client/src/components/AirportBranch.js
  client/src/components/AnimatedComponent.js
  client/src/pages/ReservationIntro.js
  client/src/styles/pages/reservationIntro.scss
Labels: refactor

#113 [#99] 헤더, 푸터 스타일 수정
  client/src/assets/logo-facebook.png
  client/src/assets/logo-footer.png
  client/src/assets/logo-header.png
  client/src/assets/logo-link.png
  client/src/assets/logo-url.png
  client/src/assets/logo-x.png
  client/src/assets/logo.png
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/Main.js
  client/src/styles/components/footer.scss
  client/src/styles/components/header.scss
  client/src/styles/pages/main.scss
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
Labels: design

#115 [#76] 디자인 변경에 따른 메인 페이지 퍼블리싱
  client/src/assets/Info-area-image1.png
  client/src/assets/info-area-image2.png
  client/src/assets/info-area-image3.png
  client/src/assets/info-area-image4.png
  client/src/assets/info-area-image5.png
  client/src/assets/main.png
  client/src/pages/Main.js
  client/src/styles/pages/main.scss
Labels: feat, refactor, design

#117 Design/#114 mypage scss 변수
  client/src/pages/Main.js
  client/src/styles/components/header.scss
  client/src/styles/pages/myPage.scss
  client/src/styles/variables.scss
Labels: design

#123 [#118] 예약상세 페이지 구성
  client/src/assets/after-1.png
  client/src/assets/after-2.png
  client/src/assets/after-3.png
  client/src/assets/after-4.png
  client/src/assets/basemap-image.png
  client/src/assets/before-1.png
  client/src/assets/before-2.png
  client/src/assets/before-3.png
  client/src/assets/before-4.png
  client/src/assets/image-7.png
  client/src/components/ReservationCard.js
  client/src/index.js
  client/src/pages/ReservationDetail.js
  client/src/styles/components/header.scss
  client/src/styles/pages/reservationDetail.scss
  client/src/styles/styles.scss
Labels: feat

#126 [#116] 달력 기능 구현 완료
  client/src/components/Calendar.js
  client/src/components/ModalDate.js
  client/src/components/ModalHeader.js
  client/src/components/TimeSlots.js
  client/src/index.js
  client/src/pages/ReservationDate.js
  client/src/pages/ReservationModal.js
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
Labels: feat

#120 [#88] 예약 페이지 일부 구현
  client/src/api/ReservationApi.js
  client/src/components/ModalDate.js
  client/src/components/ModalHeader.js
  client/src/components/ModalInfo.js
  client/src/components/ModalService.js
  client/src/pages/ReservationModal.js
  client/src/styles/components/modalPage.scss
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
  server/src/main/java/com/genesisairport/reservation/respository/CouponRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat, design

#131 [#121] 차량 추가 등록 API
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
  server/src/main/java/com/genesisairport/reservation/request/CarRequest.java
  server/src/main/java/com/genesisairport/reservation/service/CarService.java
  server/src/main/resources/application.yml
Labels: feat

#119 [#112] 프로필 페이지 수정
  client/src/components/Modal.js
  client/src/pages/Profile.js
  client/src/styles/components/modal.scss
  client/src/styles/pages/myPage.scss
  client/src/styles/pages/profile.scss
Labels: refactor

#134 [#133] 차량 삭제 API 구현
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
  server/src/main/java/com/genesisairport/reservation/service/CarService.java
Labels: feat

#136 [#135] 프론트 폰트 통일 및 미사용 파일 정리
  client/src/pages/ReservationModal.js
  client/src/styles/components/modalHeader.scss
  client/src/styles/pages/main.scss
  client/src/styles/pages/myPage.scss
  client/src/styles/pages/reservation.scss
  client/src/styles/pages/reservationDetail.scss
  client/src/styles/pages/reservationIntro.scss
  client/src/styles/styles.scss
  client/src/styles/variables.scss
Labels: refactor

#138 [#137] 마이페이지에서 차 목록이 없으면 에러나는 현상 수정
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix

#141 [#140] cannot read properties of null 오류 수정
  client/src/pages/Main.js
Labels: fix

#145 [#144] modal-page 관련 scss파일들 복구
  client/src/components/ModalDate.js
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
Labels: fix

#147 [#146] main.js 애니메이션 버그 수정
  client/src/pages/Main.js
  client/src/styles/pages/main.scss
Labels: fix, refactor

#148 [#129] 예약상세페이지 컴포넌트 분리 및 기능 구현
  client/src/components/reservation_detail/ReservationDetailInfo.js
  client/src/components/reservation_detail/ReservationDetailResult.js
  client/src/components/reservation_detail/ReservationDetailService.js
  client/src/components/reservation_detail/ReservationDetailStep.js
  client/src/pages/ReservationDetail.js
  client/src/styles/pages/reservationDetail.scss
Labels: refactor

#154 [#151] ReservationService에 필요한 의존성 import
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix

#153 fix: scss 문제 있는 부분들 총 수정
  client/src/components/ModalDate.js
  client/src/components/ModalHeader.js
  client/src/index.js
  client/src/pages/Main.js
  client/src/pages/ReservationIntro.js
  client/src/styles/pages/main.scss
  client/src/styles/pages/myPage.scss
  client/src/styles/pages/profile.scss
  client/src/styles/pages/reservationIntro.scss
  client/src/styles/pages/reservationModal.scss
  client/src/styles/styles.scss
Labels: fix

#158 [#150] 헤더 동작 오류 수정
  client/src/components/AnimatedComponent.js
  client/src/components/Header.js
  client/src/index.js
  client/src/pages/Mypage.js
  client/src/pages/ReservationComplete.js
  client/src/pages/ReservationIntro.js
  client/src/styles/components/footer.scss
  client/src/styles/pages/reservationIntro.scss
Labels: fix

#160 [#139] 차량 등록 및 삭제 API 연동
  client/src/api/CarApi.js
  client/src/assets/icon-delete.png
  client/src/assets/image.png
  client/src/components/Modal.js
  client/src/components/ProfileCard.js
  client/src/pages/Profile.js
  client/src/styles/pages/profile.scss
Labels: feat, design

#164 [#157] 예약하기 화면에 실제 기능들 추가
  client/src/api/ReservationApi.js
  client/src/components/ModalDate.js
  client/src/components/ModalService.js
  client/src/pages/ReservationModal.js
  client/src/styles/pages/reservationModal.scss
  client/src/styles/variables.scss
  client/src/utils/dateUtils.js
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#166 fix: 쿠폰번호 입력하지 않으면 예약 불가능하게 변경
  client/src/pages/ReservationModal.js
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix

#163 [#161] 예약 내역 상세 api에 차량 대표 이미지 추가
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#170 fix: 조건문의 닫는 괄호 추가
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix

#171 feat: 차량 목록 api에 car id 추가
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
Labels: feat

#168 [#167] 프로필 차량 등록 시 모달 안 뜨던 현상 수정
  client/src/components/Modal.js
  client/src/components/ProfileCard.js
  client/src/pages/Profile.js
Labels: fix

#174 [#173] 달력에서 예약 가능한 날짜만 선택 가능하게 변경
  client/src/api/ReservationApi.js
  client/src/components/Calendar.js
  client/src/components/ModalDate.js
  client/src/styles/components/calendar.scss
  client/src/styles/pages/reservationModal.scss
Labels: feat

#176 [#125] 예약상세 페이지 애니메이션 적용
  client/src/components/reservation_detail/ReservationDetailInfo.js
  client/src/components/reservation_detail/ReservationDetailResult.js
  client/src/pages/ReservationDetail.js
  client/src/styles/pages/reservationDetail.scss
Labels: refactor, design

#175 [#122] Redis로 세션 관리
  .DS_Store
  client/src/components/Header.js
  client/src/index.js
  client/src/pages/Main.js
  client/src/pages/RedirectPage.js
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/ReservationApplication.java
  server/src/main/java/com/genesisairport/reservation/common/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/common/ResponseCode.java
  server/src/main/java/com/genesisairport/reservation/config/RedisConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/entity/Session.java
  server/src/main/java/com/genesisairport/reservation/respository/CustomerRepository.java
  server/src/main/java/com/genesisairport/reservation/respository/SessionRepository.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
  server/src/main/java/com/genesisairport/reservation/service/SessionService.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
  server/src/main/resources/application.yml
Labels: feat, refactor

#183 [#178] 헤더 애니메이션이 정상동작하도록 수정
  client/src/components/AirportBranch.js
  client/src/components/Header.js
  client/src/components/reservation_modal/ModalDate.js
  client/src/components/reservation_modal/ModalHeader.js
  client/src/components/reservation_modal/ModalInfo.js
  client/src/components/reservation_modal/ModalService.js
  client/src/pages/Reservation.js
  client/src/pages/ReservationDetail.js
  client/src/pages/ReservationModal.js
  client/src/styles/pages/myPage.scss
  client/src/styles/pages/reservationDetail.scss
Labels: feat

#186 [#185] @Builder.Default 사용
  server/src/main/java/com/genesisairport/reservation/entity/Customer.java
  server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
Labels: fix

#181 [#179] Session 엔티티 사용 코드를 HttpSession 사용 코드로 변경
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
Labels: fix

#187 fix: ArrayList 초기화
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
Labels: fix

#180 [#177] 예약내역 리스트 출발일 기준 정렬
  server/src/main/java/com/genesisairport/reservation/respository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#184 [#182] 예약완료 초기단계 설정
  server/src/main/java/com/genesisairport/reservation/respository/StepRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#192 [#188] 차량 삭제 API 연동
  client/src/pages/Profile.js
Labels: fix

#193 [#189] 예약 내역 리스트 정렬 기준 변경
  server/src/main/java/com/genesisairport/reservation/respository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
Labels: refactor

#194 [#190] Step 엔티티 타입 변경
  server/src/main/java/com/genesisairport/reservation/entity/Step.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat

#196 [#195] 로그아웃 후에도 로그인 상태의 헤더가 출력되는 문제 해결
  client/src/components/Header.js
Labels: feat

#197 [#191] 메인페이지에서 이동시 발생하는 style 오류 해결
  client/src/components/Header.js
  client/src/components/reservation_detail/ReservationDetailInfo.js
  client/src/components/reservation_detail/ReservationDetailStep.js
  client/src/pages/Main.js
Labels: fix

#201 [#200] 쿠키 생성 안 되는 문제 해결
  client/src/api/Settings.js
  client/src/components/Header.js
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/TextController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
  server/src/main/resources/application.yml
Labels: fix, refactor

#203 [#202] CORS 문제 해결
  client/src/api/Settings.js
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
Labels: fix

#205 [#204] 공통 예외 처리
  server/src/main/java/com/genesisairport/reservation/common/GeneralException.java
  server/src/main/java/com/genesisairport/reservation/common/GlobalExceptionHandler.java
Labels: feat

#209 [#206] 관리자 프론트 디렉토리 생성
  admin/.gitignore
  admin/package-lock.json
  admin/package.json
  admin/public/index.html
  admin/src/api/dummy.js
  admin/src/assets/progress-arrow.svg
  admin/src/components/SideBar.js
  admin/src/fonts/GenesisSansHeadKRLight.woff2
  admin/src/fonts/GenesisSansHeadKRRegular.woff2
  admin/src/fonts/GenesisSansTextKRRegular.woff2
  admin/src/index.js
  admin/src/pages/Main.js
  admin/src/pages/NotFound.js
  admin/src/styles/reset.scss
  admin/src/styles/styles.scss
  admin/src/styles/variables.scss
Labels: setup

#214 [#207] 세션 인터셉터 추가
  client/src/api/Settings.js
  server/src/main/java/com/genesisairport/reservation/common/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/common/SessionInterceptor.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
Labels: feat

#216 [#212] 정비 전후 사진 업로드 API
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/common/enums/ResponseCode.java
  server/src/main/java/com/genesisairport/reservation/common/exception/GeneralException.java
  server/src/main/java/com/genesisairport/reservation/common/model/DataResponseDto.java
  server/src/main/java/com/genesisairport/reservation/common/model/ResponseDto.java
  server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
  server/src/main/java/com/genesisairport/reservation/common/util/GlobalExceptionHandler.java
  server/src/main/java/com/genesisairport/reservation/common/util/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/config/S3Config.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/TextController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/AvailableTime.java
  server/src/main/java/com/genesisairport/reservation/entity/Car.java
  server/src/main/java/com/genesisairport/reservation/entity/CarImage.java
  server/src/main/java/com/genesisairport/reservation/entity/Coupon.java
  server/src/main/java/com/genesisairport/reservation/entity/Customer.java
  server/src/main/java/com/genesisairport/reservation/entity/MaintenanceImage.java
  server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
  server/src/main/java/com/genesisairport/reservation/entity/Step.java
  server/src/main/java/com/genesisairport/reservation/respository/MaintenanceImageRepository.java
  server/src/main/java/com/genesisairport/reservation/service/S3Service.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
Labels: feat, admin

#222 [#218] 관리자 로그인, 로그아웃 API 구현
  server/src/main/java/com/genesisairport/reservation/controller/admin/AdminAccountController.java
  server/src/main/java/com/genesisairport/reservation/entity/Admin.java
  server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
  server/src/main/java/com/genesisairport/reservation/respository/AdminRepository.java
  server/src/main/java/com/genesisairport/reservation/service/SessionService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AdminAccountService.java
Labels: feat, admin

#219 [#215] 예약 단계 삭제 api
  server/src/main/java/com/genesisairport/reservation/common/ProgressStage.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AdminReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/Car.java
  server/src/main/java/com/genesisairport/reservation/entity/CarImage.java
  server/src/main/java/com/genesisairport/reservation/entity/Coupon.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
  server/src/main/java/com/genesisairport/reservation/entity/Step.java
  server/src/main/java/com/genesisairport/reservation/respository/StepRepository.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AdminReservationService.java
Labels: feat, admin

#228 [#225] admin 프론트 공통 컴포넌트 구현
  admin/package-lock.json
  admin/package.json
  admin/src/components/Button.js
  admin/src/components/SideBar.js
  admin/src/components/svg/MenuImage.js
  admin/src/components/svg/ProfileImage.js
  admin/src/index.js
  admin/src/pages/Main.js
  admin/src/pages/TestPage.js
  admin/src/styles/components/button.scss
  admin/src/styles/components/sideBar.scss
  admin/src/styles/reset.scss
  admin/src/styles/styles.scss
  admin/src/styles/variables.scss
  admin/src/util/states.js
Labels: feat, refactor, admin

#229 [#226] 관리자 로그인 버그 해결, 런타임 에러 해결
  server/src/main/java/com/genesisairport/reservation/common/util/SessionUtil.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/CarController.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/UserController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AdminAccountController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AdminReservationController.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
Labels: fix

#230 [#211] 관리자 예약 리스트 검색 API 구현
  server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AdminReservationController.java
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/CarImageRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/CarRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/CouponRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/CustomerRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/MaintenanceImageRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/RepairShopRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/RepairShopRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/RepairShopRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/repository/StepRepository.java
  server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
  server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
  server/src/main/java/com/genesisairport/reservation/service/AuthService.java
  server/src/main/java/com/genesisairport/reservation/service/CarService.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AAccountService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AdminReservationService.java
Labels: feat, admin

#232 [#227] 정비 결과 코멘트 업데이트 api 개발
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
  server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
Labels: feat, admin

#234 feat: 예약관리 상세 퍼블리싱
  admin/src/components/Button.js
  admin/src/components/SideBar.js
  admin/src/components/svg/LogoutImage.js
  admin/src/index.js
  admin/src/pages/RservationDetail.js
  admin/src/styles/components/button.scss
  admin/src/styles/components/sideBar.scss
  admin/src/styles/pages/reservationDetail.scss
  admin/src/styles/styles.scss
Labels: feat, admin

#235 [#210] 예약가능시간 관련 api 개발
  server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AShopController.java
  server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
  server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AShopService.java
Labels: feat, admin

#238 [#217] 관리자 예약 목록 페이지 퍼블리싱
  admin/package-lock.json
  admin/package.json
  admin/src/assets/arrow.svg
  admin/src/components/CustomCalendar.js
  admin/src/index.js
  admin/src/pages/ReservationList.js
  admin/src/styles/components/customCalendar.scss
  admin/src/styles/components/sideBar.scss
  admin/src/styles/pages/reservationList.scss
  admin/src/styles/styles.scss
  admin/src/styles/variables.scss
Labels: feat, admin

#240 [#221] 관리자 계정 조회 api 개발
  server/src/main/java/com/genesisairport/reservation/common/model/PageInfo.java
  server/src/main/java/com/genesisairport/reservation/common/model/PageResponseDto.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
  server/src/main/java/com/genesisairport/reservation/entity/Admin.java
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
  server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AAccountService.java
Labels: feat, admin

#242 [#241] 테이블 및 관련 api 수정
  client/src/components/reservation_detail/ReservationDetailResult.js
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/MaintenanceImage.java
  server/src/main/java/com/genesisairport/reservation/entity/Step.java
  server/src/main/java/com/genesisairport/reservation/repository/StepRepository.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
Labels: refactor, admin

#244 [#243] 관리자 조회 api 데이터 수신 방식 수정
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
Labels: fix, admin

#245 [#237] 예약 상세 페이지 API기능 연결
  admin/.gitignore
  admin/src/api/ReservationApi.js
  admin/src/api/Settings.js
  admin/src/api/dummy.js
  admin/src/components/Button.js
  admin/src/components/SideBar.js
  admin/src/components/modal/AddImageModal.js
  admin/src/index.js
  admin/src/pages/ReservationDetail.js
  admin/src/pages/RservationDetail.js
  admin/src/styles/components/button.scss
  admin/src/styles/components/infoTable.scss
  admin/src/styles/components/modal.scss
  admin/src/styles/components/reservationList.scss
  admin/src/styles/styles.scss
  server/src/main/java/com/genesisairport/reservation/common/SessionInterceptor.java
  server/src/main/java/com/genesisairport/reservation/common/enums/ProgressStage.java
  server/src/main/java/com/genesisairport/reservation/common/enums/ResponseCode.java
  server/src/main/java/com/genesisairport/reservation/common/util/GlobalExceptionHandler.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/MaintenanceImage.java
  server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/S3Service.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AShopService.java
Labels: feat, fix, refactor, admin

#250 [#249] 관리자 계정 조회 api fix
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryImpl.java
Labels: fix, admin

#251 [#233] 관리자 계정 조회 페이지 퍼블리싱 및 Api 연동
  admin/.gitignore
  admin/src/api/AccountApi.js
  admin/src/api/Settings.js
  admin/src/components/BtnDark.js
  admin/src/components/BtnLight.js
  admin/src/components/Button.js
  admin/src/components/Pagination.js
  admin/src/index.js
  admin/src/pages/Account.js
  admin/src/pages/Main.js
  admin/src/pages/ReservationDetail.js
  admin/src/pages/ReservationList.js
  admin/src/pages/TestPage.js
  admin/src/styles/components/account.scss
  admin/src/styles/styles.scss
Labels: feat, design, admin

#246 [#239] 관리자 예약 관리 페이지 API 연결
  admin/src/api/ReservationApi.js
  admin/src/components/CustomCalendar.js
  admin/src/components/SideBar.js
  admin/src/pages/ReservationList.js
  admin/src/styles/pages/reservationList.scss
  admin/src/styles/styles.scss
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
Labels: feat, design, admin

#247 [#220, #248] 관리자 로그인 페이지 퍼블리싱
  admin/src/pages/Main.js
  admin/src/styles/pages/main.scss
  admin/src/styles/styles.scss
  server/src/main/java/com/genesisairport/reservation/common/util/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
Labels: feat, design, admin

#256 [#252] 관리자 예약 조회 Api 페이지네이션 구현
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryCustom.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepositoryImpl.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
Labels: feat, admin

#260 [#260] S3 관련 기능 이용 시 인스턴스 자체에 내장된 aws config 값을 로딩해서 사용하도록 변경
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/config/S3Config.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
Labels: refactor

#263 [#261] 예약하기 API 동시성 처리
  server/src/main/java/com/genesisairport/reservation/common/enums/RedisKey.java
  server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
  server/src/main/java/com/genesisairport/reservation/common/util/ConcurrencyManager.java
  server/src/main/java/com/genesisairport/reservation/common/util/GlobalExceptionHandler.java
  server/src/main/java/com/genesisairport/reservation/common/util/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/common/util/SessionUtil.java
  server/src/main/java/com/genesisairport/reservation/config/S3Config.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/entity/AvailableTime.java
  server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepository.java
  server/src/main/java/com/genesisairport/reservation/repository/ReservationRepository.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: feat, refactor

#264 [#253] 세션 클러스터링 오류 해결
  admin/src/components/BtnLight.js
  admin/src/components/modal/AddImageModal.js
  admin/src/pages/ReservationDetail.js
  admin/src/pages/ReservationList.js
  server/build.gradle
  server/src/main/java/com/genesisairport/reservation/ReservationApplication.java
  server/src/main/java/com/genesisairport/reservation/common/SessionInterceptor.java
  server/src/main/java/com/genesisairport/reservation/common/util/SessionUtil.java
  server/src/main/java/com/genesisairport/reservation/config/RedisConfig.java
  server/src/main/java/com/genesisairport/reservation/config/RedisHttpSessionConfig.java
  server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
  server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
  server/src/main/resources/application.yml
Labels: fix, refactor

#272 [#271] 정비소 관리 페이지 오류 수정 및 기타 QA
  admin/src/components/list/TableRow.js
  admin/src/components/modal/AvailableTimeModal.js
  admin/src/pages/AccountList.js
  admin/src/pages/ReservationDetail.js
  admin/src/pages/ReservationList.js
  client/src/api/ReservationApi.js
  client/src/api/UserApi.js
  client/src/components/Modal.js
  client/src/components/SellNameSelector.js
  client/src/components/reservation_modal/ModalDate.js
  client/src/components/reservation_modal/ModalInfo.js
  client/src/pages/ReservationModal.js
  client/src/styles/styles.scss
  server/src/main/java/com/genesisairport/reservation/common/util/ConcurrencyManager.java
  server/src/main/java/com/genesisairport/reservation/common/util/RedisUtil.java
  server/src/main/java/com/genesisairport/reservation/service/UserService.java
  server/src/main/java/com/genesisairport/reservation/service/admin/AShopService.java
Labels: feat, fix, design, admin

#276 [#275] QA 이슈 수정
  admin/src/api/ReservationApi.js
  admin/src/components/common/SideBar.js
  admin/src/components/infotable/InfoGrid.js
  admin/src/components/infotable/InfoSteps.js
  admin/src/components/list/TableRow.js
  admin/src/components/modal/SimpleModal.js
  admin/src/pages/Login.js
  admin/src/pages/ReservationDetail.js
  admin/src/pages/ReservationList.js
  admin/src/styles/components/infoTable.scss
  admin/src/styles/components/list.scss
  admin/src/styles/variables.scss
  admin/src/util/states.js
  client/src/components/reservation_modal/ModalDate.js
  server/src/main/java/com/genesisairport/reservation/common/exception/GeneralException.java
  server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
  server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
  server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
  server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Labels: fix
